# 数据库配置文件

databases:
  default:
    host: localhost
    port: 3306
    user: root
    password: ""
    dbname: test

  development:
    host: localhost
    port: 3306
    user: dev_user
    password: dev_password
    dbname: dev_db

  production:
    host: prod.db.host
    port: 3306
    user: prod_user
    password: prod_password
    dbname: prod_db